name: publish
on: [release]
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: karsajobs
jobs:
    publish-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                submodules: recursive
    
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
        
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
            with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
          - name: Build the app Docker image with version as tag
            uses: docker/build-push-action@v4
            with:
                context: .
                push: true
                labels: ${{ steps.meta.outputs.labels }}
                tags: ${{ steps.meta.outputs.tags }}, latest